### ISSUE TITLE
Update or Replace content of already delivered notification

### ISSUE THREAD

**Issue by jayan2019** [evennit/notifee-expo-plugin#6]
Hi thanks for the good plugin, 

Can this plugin update the `title` & `body` of the notification which is already available in iOS device by identifying id or some other unique key.
If yes, how my `notifee_options` need to be formatted!

**Comment by Kasendwa** [comment]
Hi @jayan2019, this is not what this plugin does. 

But here is what you need for this scenario: https://notifee.app/react-native/docs/displaying-a-notification#updating-a-notification

**Comment by jayan2019** [comment]
Hi @Kasendwa, Thank you but data only notification sometimes delay or some time skipped by device.
Anyhow thanks a lot for the package :v:

**Comment by Kasendwa** [comment]
> Hi @Kasendwa, Thank you but data only notification sometimes delay or some time skipped by device. Anyhow thanks a lot for the package ✌️

Hi @jayan2019 when you use data only notifications, just ensure you make use of the `contentAvailable` and `priority` values. That would ensure iOS gives them immediate attention

```javascript
apns: {
    payload: {
        ...[others],
        contentAvailable: true,
        priority: 10
    }
}
```
